stages:
  - image
  - sync

build_image:
  stage: image
  when: manual
  tags:
    - docker-image-build
  script: "echo Building image ${CI_REGISTRY_IMAGE} ..."
  variables:
    CONTEXT_DIR: "docker"
    TO: "${CI_REGISTRY_IMAGE}:latest"
    NO_CACHE: "true"

quick_comparison:
  stage: sync
  tags:
    - docker
  image: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - echo "${KRB_PASS}" | kinit ${KRB_USER}@CERN.CH
    - klist
    - PYTHONPATH="${PWD}:${PYTHONPATH}" python sync --data-dir data --flush --ci --table-format pipe "write_all()"
    - for f in $( ls data/tables/*.md ); do pandoc "$f" -o "${f%.*}.html"; done
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - data/tables
      - data/plots
