datasets:
  data_mu:
    files:
      - /store/data/Run2018D/SingleMuon/MINIAOD/22Jan2019-v2/110000/0011A0F3-23A3-D444-AD4D-2A2FFAE23796.root
    test_events: [261258553, 162739046, 368407055, 544498301, 578332126]
    groups:
      CERN:
        files:
          mutau: /afs/cern.ch/user/m/mrieger/public/hbt/sync_run2_pp_2018/sync1/data_mu.root
        transform: transform_cern_2018
      MIBLLR:
        files:
          mutau: /afs/cern.ch/user/d/dzuolo/public/Mu2018D_Sync_12mar20.root
        transform: transform_mibllr_2018
      PIKOSI:
        files:
          mutau: /eos/home-m/mdidomen/sync_2020_big/sync_single_muon_2018.root
        transform: transform_pikosi_2018

  data_e:
    files:
      - /store/data/Run2018D/EGamma/MINIAOD/22Jan2019-v2/110000/2FD9167C-A197-E749-908D-3809F7B83A23.root
    test_events: [1379040063, 1342706563, 166666955, 165250764, 1384106641]
    groups:
      CERN:
        files:
          etau: /afs/cern.ch/user/m/mrieger/public/hbt/sync_run2_pp_2018/sync1/data_e.root
        transform: transform_cern_2018
      MIBLLR:
        files:
          etau: /afs/cern.ch/user/d/dzuolo/public/Ele2018D_Sync_12mar20.root
        transform: transform_mibllr_2018
      PIKOSI:
        files:
          etau: /eos/home-m/mdidomen/sync_2020_big/sync_single_electron_2018.root
        transform: transform_pikosi_2018

  data_tau:
    files:
      - /store/data/Run2018D/Tau/MINIAOD/PromptReco-v2/000/320/673/00000/3ACE6677-E797-E811-B689-FA163E0FDAE6.root
    test_events: [709351329, 755877979, 1080920610, 1533605828, 1869609222]
    groups:
      CERN:
        files:
          tautau: /afs/cern.ch/user/m/mrieger/public/hbt/sync_run2_pp_2018/sync1/data_tau.root
        transform: transform_cern_2018
      PIKOSI:
        files:
          tautau: /eos/home-m/mdidomen/sync_2020_big/sync_single_tau_2018.root
        transform: transform_pikosi_2018

  mc_hh_vbf:
    files:
      - /store/mc/RunIIAutumn18MiniAOD/VBFHHTo2B2Tau_CV_1_C2V_1_C3_1_TuneCP5_PSWeights_13TeV-madgraph-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/250000/F22484D3-E820-F040-8E63-0864695D025B.root
    test_events: [96136, 96464, 96731, 98026, 99382]
    groups:
      CERN:
        files:
          all: /afs/cern.ch/user/m/mrieger/public/hbt/sync_run2_pp_2018/sync1/mc_hh_vbf.root
        transform: transform_cern_2018
      MIBLLR:
        files:
          all: /afs/cern.ch/work/f/fbrivio/public/hh_syncFeb2020/VBF18_Sync_12mar20.root
        transform: transform_mibllr_2018
      PIKOSI:
        files:
          mutau: /eos/home-m/mdidomen/sync_2020_big/sync_vbf_hh_muTau_2018.root
          etau: /eos/home-m/mdidomen/sync_2020_big/sync_vbf_hh_eTau_2018.root
          tautau: /eos/home-m/mdidomen/sync_2020_big/sync_vbf_hh_tauTau_2018.root
        transform: transform_pikosi_2018

categories:
  all: ((n_jets >= 0))
  mutau, OS: ((pairType == 0) & (isOS == 1))
  mutau, SS: ((pairType == 0) & (isOS == 0))
  etau, OS: ((pairType == 1) & (isOS == 1))
  etau, SS: ((pairType == 1) & (isOS == 0))
  tautau, OS: ((pairType == 2) & (isOS == 1))
  tautau, SS: ((pairType == 2) & (isOS == 0))

variables:
  - run
  - lumi
  - event
  - pairType
  - isOS
  - rho
  - pu
  - n_jets
  - n_btags
  # - electron_pt
  # - electron_eta
  # - electron_phi
  # - electron_charge
  # - electron_iso
  # - muon_pt
  # - muon_eta
  # - muon_phi
  # - muon_charge
  # - muon_iso
  - tau1_pt
  - tau1_eta
  - tau1_phi
  # - tau1_charge
  - tau1_decay_mode
  # - tau1_id_byDeepTau2017v2p1VSjetraw
  # - tau2_pt
  # - tau2_eta
  # - tau2_phi
  # - tau2_charge
  # - tau2_decay_mode
  # - tau2_id_byDeepTau2017v2p1VSjetraw
  - jet1_pt
  - jet1_eta
  - jet1_phi
  # - jet1_btag
  - jet2_pt
  - jet2_eta
  - jet2_phi
  # - jet2_btag
  # - met_pt
  # - met_phi
  # - met_pt_uncorrected
  # - met_phi_uncorrected
  # - ll_m
  # - ll_dr
  # - fastmtt_likelihood
  # - fastmtt_m
