datasets:
  hh:
    files:
      - /store/mc/Run3Summer22NanoAODv12/GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00_LHEweights_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/50000/992697da-4a10-4435-b63a-413f6d33517e.root
    test_events: [224012, 238597, 238638, 239072, 242573]
    groups:
      cf:
        files:
          - /afs/cern.ch/work/m/mrieger/public/hbt/run3_sync/sync_hh_ggf_hbb_htt_kl1_kt1_powheg_0.csv
        transform: null
      cclub:
        files:
          # TODO: change
          - /afs/cern.ch/work/m/mrieger/public/hbt/run3_sync/sync_hh_ggf_hbb_htt_kl1_kt1_powheg_0.csv
        transform: null

categories:
  all: ((channel_id >= -1))
  mutau, OS: ((channel_id == 1) & (os == 1))
  mutau, SS: ((channel_id == 1) & (os == 0))
  etau, OS: ((channel_id == 2) & (os == 1))
  etau, SS: ((channel_id == 2) & (os == 0))
  tautau, OS: ((channel_id == 3) & (os == 1))
  tautau, SS: ((channel_id == 4) & (os == 0))

variables:
  # Event
  - event
  - run
  - lumi
  - channel_id
  - os
  # Jets
  - jet1_pt
  - jet1_eta
  - jet1_phi
  - jet1_mass
  - jet2_pt
  - jet2_eta
  - jet2_phi
  - jet2_mass
  # Lepton
  - lep1_pt
  - lep1_eta
  - lep1_phi
  - lep1_charge
  - lep1_deeptauvsjet
  - lep2_pt
  - lep2_eta
  - lep2_phi
  - lep2_charge
  - lep2_deeptauvsjet
  # Electron
  - electron1_charge
  - electron1_eta
  - electron1_mass
  - electron1_phi
  - electron1_pt
  - electron2_charge
  - electron2_eta
  - electron2_mass
  - electron2_phi
  - electron2_pt
  # Muon
  - muon1_charge
  - muon1_eta
  - muon1_mass
  - muon1_phi
  - muon1_pt
  - muon2_charge
  - muon2_eta
  - muon2_mass
  - muon2_phi
  - muon2_pt
  # Tau
  - tau1_charge
  - tau1_eta
  - tau1_mass
  - tau1_phi
  - tau1_pt
  - tau2_charge
  - tau2_eta
  - tau2_mass
  - tau2_phi
  - tau2_pt
  # MET
  - met1_pt
  - met1_phi
  # FatJet
  - fatjet1_eta
  - fatjet1_mass
  - fatjet1_phi
  - fatjet1_pt
  - fatjet1_tau1
  - fatjet1_tau2
  - fatjet1_tau3
  - fatjet1_tau4
  - fatjet2_eta
  - fatjet2_mass
  - fatjet2_phi
  - fatjet2_pt
  - fatjet2_tau1
  - fatjet2_tau2
  - fatjet2_tau3
  - fatjet2_tau4
