datasets:
  hh:
    lfn: /store/mc/Run3Summer22NanoAODv12/GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00_LHEweights_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/50000/992697da-4a10-4435-b63a-413f6d33517e.root
    test_events: [224012, 238597, 238638, 239072, 242573]
    groups:
      cf:
        files:
          - /afs/cern.ch/work/m/mrieger/public/hbt/run3_sync/sync_hh_ggf_hbb_htt_kl1_kt1_powheg_0_v5.csv
        missing_value: -99999
        transform: null
      cclub:
        files:
          - /afs/cern.ch/work/j/jmotta/public/run3_2022_preEE/ggHH_kl_1_kt_1_c2_0_hbbhtt/cat_synch/Synch4_noHHBTag/data_0.csv
        missing_value: -999
        transform: cclub_to_cf

categories:
  - name: all
    expression: ((channel_id >= -1))
    label: All
  - name: etau_os
    expression: ((channel_id == 1) & (os == 1))
    label: etau OS
  - name: etau_ss
    expression: ((channel_id == 1) & (os == 0))
    label: etau SS
  - name: mutau_os
    expression: ((channel_id == 1) & (os == 1))
    label: mutau OS
  - name: mutau_ss
    expression: ((channel_id == 1) & (os == 0))
    label: mutau SS
  - name: tautau_os
    expression: ((channel_id == 1) & (os == 1))
    label: tautau OS
  - name: tautau_ss
    expression: ((channel_id == 1) & (os == 0))
    label: tautau SS
  - name: ee_os
    expression: ((channel_id == 1) & (os == 1))
    label: ee OS
  - name: ee_ss
    expression: ((channel_id == 1) & (os == 0))
    label: ee SS
  - name: mumu_os
    expression: ((channel_id == 1) & (os == 1))
    label: mumu OS
  - name: mumu_ss
    expression: ((channel_id == 1) & (os == 0))
    label: mumu SS
  - name: emu_os
    expression: ((channel_id == 1) & (os == 1))
    label: emu OS
  - name: emu_ss
    expression: ((channel_id == 1) & (os == 0))
    label: emu SS

variables:
  # Event
  - name: event
    type: int
  - name: run
    type: int
  - name: lumi
    type: int
  - name: channel_id
    type: int
    labels: {1: "etau", 2: "mutau", 3: "tautau", 4: "ee", 5: "mumu", 6: "emu"}
  - name: os
    type: int
    labels: {0: "SS", 1: "OS"}
  - name: deterministic_seed
    type: int
  # Jets
  - jet1_pt
  - jet1_eta
  - jet1_phi
  - jet1_mass
  - name: jet1_deterministic_seed
    type: int
  - jet2_pt
  - jet2_eta
  - jet2_phi
  - jet2_mass
  - name: jet2_deterministic_seed
    type: int
  # Lepton
  - lep1_pt
  - lep1_eta
  - lep1_phi
  - name: lep1_charge
    type: int
    labels: {-1: "-1", 0: "0", 1: "1"}
  - lep1_deeptauvsjet
  - lep2_pt
  - lep2_eta
  - lep2_phi
  - name: lep2_charge
    type: int
    labels: {-1: "-1", 0: "0", 1: "1"}
  - lep2_deeptauvsjet
  # MET
  - met_pt
  - met_phi
  # FatJet
  - fatjet1_pt
  - fatjet1_eta
  - fatjet1_phi
  - fatjet1_mass
  - fatjet2_pt
  - fatjet2_eta
  - fatjet2_phi
  - fatjet2_mass
