datasets:
  hh:
    files:
      - /store/mc/Run3Summer22NanoAODv12/GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00_LHEweights_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/50000/992697da-4a10-4435-b63a-413f6d33517e.root
    test_events: [224012, 238597, 238638, 239072, 242573]
    groups:
      uhh:
        files:
          - /afs/desy.de/user/w/wiedersb/sync_dummy_files/sync_hh_ggf_hbb_htt_kl1_kt1_powheg_0.csv
        transform: null
      # uzh:
      #   files:
      #     - /afs/desy.de/user/w/wiedersb/sync_dummy_files/uhz.csv
      #   transform: null
      central_nano:
        files:
          - /afs/desy.de/user/w/wiedersb/sync_dummy_files/sync_hh_ggf_hbb_htt_kl1_kt1_powheg_0_central_overlap.csv
        transform: null

categories:
  all: ((channel_id >= -1))
  mutau, OS: ((channel_id == 1) & (os == 1))
  mutau, SS: ((channel_id == 1) & (os == 0))
  etau, OS: ((channel_id == 2) & (os == 1))
  etau, SS: ((channel_id == 2) & (os == 0))
  tautau, OS: ((channel_id == 3) & (os == 1))
  tautau, SS: ((channel_id == 4) & (os == 0))

variables:
# Event
  - event
  - run
  - lumi
  - channel_id
  - os
# Jets
  - jet1_pt
  - jet1_eta
  - jet1_phi
  - jet1_mass
  - jet2_pt
  - jet2_eta
  - jet2_phi
  - jet2_mass
# Lepton
  - lep1_pt
  - lep1_eta
  - lep1_phi
  - lep1_charge
  - lep1_deeptauvsjet
  - lep2_pt
  - lep2_eta
  - lep2_phi
  - lep2_charge
  - lep2_deeptauvsjet
# Electron
  - electron1_charge
  - electron1_eta
  - electron1_mass
  - electron1_phi
  - electron1_pt
  - electron2_charge
  - electron2_eta
  - electron2_mass
  - electron2_phi
  - electron2_pt
# Muon
  - muon1_charge
  - muon1_eta
  - muon1_mass
  - muon1_phi
  - muon1_pt
  - muon2_charge
  - muon2_eta
  - muon2_mass
  - muon2_phi
  - muon2_pt
# Tau
  - tau1_charge
  - tau1_eta
  - tau1_mass
  - tau1_phi
  - tau1_pt
  - tau2_charge
  - tau2_eta
  - tau2_mass
  - tau2_phi
  - tau2_pt
# MET
  - met1_covXX
  - met1_covXY
  - met1_covYY
  - met1_phi
  - met1_pt
  - met1_significance
# FatJet
  - fatjet1_eta
  - fatjet1_mass
  - fatjet1_phi
  - fatjet1_pt
  - fatjet1_tau1
  - fatjet1_tau2
  - fatjet1_tau3
  - fatjet1_tau4
  - fatjet2_eta
  - fatjet2_mass
  - fatjet2_phi
  - fatjet2_pt
  - fatjet2_tau1
  - fatjet2_tau2
  - fatjet2_tau3
  - fatjet2_tau4





  # #  Electron
  # - Electron_charge
  # - Electron_convVeto
  # - Electron_dxy
  # - Electron_dz
  # - Electron_eta
  # - Electron_hoe
  # - Electron_ip3d
  # - Electron_jetIdx
  # - Electron_mass
  # - Electron_mvaTTH
  # - Electron_phi
  # - Electron_pt
  # - Electron_tightCharge
  # - #  Muon
  # - Muon_charge
  # - Muon_dxy
  # - Muon_dz
  # - Muon_eta
  # - Muon_jetIdx
  # - Muon_jetNDauCharged
  # - Muon_looseId
  # - Muon_mass
  # - Muon_phi
  # - Muon_pt
  # - # Tau
  # - Tau_charge
  # - Tau_chargedIso
  # - Tau_decayMode
  # - Tau_decayModePNet
  # - Tau_dxy
  # - Tau_dz
  # - Tau_eleIdx
  # - Tau_eta
  # - Tau_idDecayModeNewDMs
  # - Tau_idDeepTau2017v2p1VSe
  # - Tau_idDeepTau2017v2p1VSjet
  # - Tau_idDeepTau2017v2p1VSmu
  # - Tau_idDeepTau2018v2p5VSe
  # - Tau_idDeepTau2018v2p5VSjet
  # - Tau_idDeepTau2018v2p5VSmu
  # - Tau_jetIdx
  # - Tau_mass
  # - Tau_phi
  # - Tau_pt
  # - Tau_ptCorrPNet
  # - Tau_qConfPNet
  # - Tau_rawDeepTau2017v2p1VSe
  # - Tau_rawDeepTau2017v2p1VSjet
  # - Tau_rawDeepTau2017v2p1VSmu
  # - Tau_rawDeepTau2018v2p5VSe
  # - Tau_rawDeepTau2018v2p5VSjet
  # - Tau_rawDeepTau2018v2p5VSmu
  # - #  FatJet
  # - FatJet_btagDDBvLV2
  # - FatJet_btagDDCvBV2
  # - FatJet_btagDDCvLV2
  # - FatJet_btagDeepB
  # - FatJet_btagHbb
  # - FatJet_eta
  # - FatJet_mass
  # - FatJet_nBHadrons
  # - FatJet_nCHadrons
  # - FatJet_particleNetWithMass_H4qvsQCD
  # - FatJet_particleNetWithMass_HbbvsQCD
  # - FatJet_particleNetWithMass_HccvsQCD
  # - FatJet_particleNetWithMass_QCD
  # - FatJet_particleNetWithMass_TvsQCD
  # - FatJet_particleNetWithMass_WvsQCD
  # - FatJet_particleNetWithMass_ZvsQCD
  # - FatJet_particleNet_QCD
  # - FatJet_particleNet_QCD0HF
  # - FatJet_particleNet_QCD1HF
  # - FatJet_particleNet_QCD2HF
  # - FatJet_particleNet_XbbVsQCD
  # - FatJet_particleNet_XccVsQCD
  # - FatJet_particleNet_XggVsQCD
  # - FatJet_particleNet_XqqVsQCD
  # - FatJet_particleNet_XteVsQCD
  # - FatJet_particleNet_XtmVsQCD
  # - FatJet_particleNet_XttVsQCD
  # - FatJet_particleNet_massCorr
  # - FatJet_phi
  # - FatJet_pt
  # - FatJet_tau1
  # - FatJet_tau2
  # - FatJet_tau3
  # - FatJet_tau4
  # #  MET
  # - MET_covXX
  # - MET_covXY
  # - MET_covYY
  # - MET_phi
  # - MET_pt
  # - MET_significance
  # - MET_sumEt
  # - MET_sumPtUnclustered
  # - DeepMETResolutionTune_phi
  # - DeepMETResolutionTune_pt
  # - DeepMETResponseTune_phi
  # - DeepMETResponseTune_pt
  # # n
  # - nElectron
  # - nFatJet
  # - nFsrPhoton
  # - nGenJet
  # - nGenJetAK8
  # - nGenPart
  # - nGenVisTau
  # - nJet
  # - nMuon
  # - nTau
  # - nboostedTau

